#!/bin/bash

set -e

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

pidfile=${DIR}/tillweb.pid

cd "${DIR}/tillweb"

export DJANGO_SETTINGS_MODULE=tillweb.settings_production
export LANG=en_GB.UTF8
export LC_CTYPE=en_GB.UTF8
mkdir -p "${DIR}/static"
python manage.py collectstatic --noinput
uwsgi_python --stop ${pidfile} || echo "No daemon was running"
exec uwsgi_python \
     --socket 127.0.0.1:3861 \
     --wsgi-file tillweb/wsgi.py \
     --threads 4 \
     --master \
     --pidfile ${pidfile} \
     --daemonize ${DIR}/uwsgi.log
