# Generated by Django 6.0.2 on 2026-02-13 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tillweb', '0003_auto_20190722_1141'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='access',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='access',
            name='till',
        ),
        migrations.RemoveField(
            model_name='access',
            name='user',
        ),
        migrations.DeleteModel(
            name='Till',
        ),
        migrations.DeleteModel(
            name='Access',
        ),
    ]
