.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH RUNTILL 1 "2015-07-22"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
runtill \- start up a till or stock control terminal
.SH SYNOPSIS
.B runtill
.RI "[ options ] action"
.SH DESCRIPTION
This manual page documents briefly the
.B runtill
command.
.PP
.\" TeX users may be more comfortable with the \fB<whatever>\fP and
.\" \fI<whatever>\fP escape sequences to invode bold face and italics, 
.\" respectively.
\fBruntill\fP is a program that enables an instance of the quicktill
system to be started, loading its configuration from a URL.
.SH OPTIONS
This program follows the usual GNU command line syntax, with long
options starting with two dashes (\-\-).
A summary of options is included below.
.TP
.B \-h, \-\-help
Show summary of options.
.TP
.B \-\-version
Show version of program.
.TP
.B \-u, \-\-config\-url CONFIGURL
Provide the URL of the till configuration file; overrides the default
configured in /etc/quicktill/configurl
.TP
.B \-c, \-\-config\-name CONFIGNAME
Indicate which configuration to use from the global configuration file.
The default is 'default'.
.TP
.B \-t, \-\-terminal\-name TERMINALNAME
Terminal name to store for transaction lines and payments created
by this till instance. Defaults to CONFIGNAME.
.TP
.B \-d, \-\-database DATABASE
Override the database connection indicated in the configuration file.
.TP
.B \-f, \-\-user USER
User ID to use when no other user information is available (use 'listusers'
command to check IDs)
.TP
.B \-y, \-\-log\-config LOGCONFIG
Specify a YAML log configuration file.
.TP
.B \-l, \-\-logfile=LOGFILE
Specify a log filename for simple logging.
.TP
.B \-\-debug
Include debug output in the log.
.TP
.B \-\-log\-sql
Include SQL queries in the log.
.TP
.B \-\-disable\-printer
Use the null printer instead of the configured printer.
.SH ACTIONS
.TP
.B start [ \-\-nolisten ]
Run the till interactively.  Use \-n or \-\-nolisten to disable the
listening sockets for user tokens and barcodes.
.TP
.B dbshell
Starts an interactive python session with the database initialised, an
ORM session started, the first two commends being "import
quicktill.td" and "from quicktill.models import *".
.TP
.B syncdb
Create database tables that are missing from the database.
.TP
.B flushdb [ \-\-really ]
Remove tables from the database.  If the database contains more than
two sessions of data then this command will refuse to run unless you
supply the \-\-really option.
.TP
.B dbsetup [ dbfile ]
With no positional argument, outputs a template database setup file on
STDOUT.  With one argument, reads and processes a database setup file.
.TP
.B checkdb
Compare the current database schema with one created from "syncdb" on
an empty database, and output SQL statements to update it to match.
Uses apgdiff and will fail if it is not installed.  Do not pipe the
output of this command directly to psql; check it first!
.TP
.B adduser fullname shortname usertoken
Adds a superuser to the database.  This is necessary during setup;
that user can then create new ordinary users.
.TP
.B listusers
List active users.
.TP
.B totals [ \-\-days DAYS ]
Display a table of session totals, by default for the last 40 days.
Override this with the \-\-days option.
.TP
.B twitter-auth [ \-\-consumer-key KEY ] [ \-\-consumer-secret SECRET ]
Generate tokens for Twitter login; produces a fragment of code to
be copied into the configuration file.
.TP
.B config [ \-\-set ] [ key ] [ value ]
View or modify configuration keys.
.TP
.B show-usertoken [ \-\-port PORT ]
Listen for user tokens; output the first received token and then
exit. Helpful during initial setup to view a token to use with
the 'adduser' command.

.SH AUTHOR
.B quicktill
was written by <steve@assorted.org.uk>.
