.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH RUNTILL 1 "2008-11-16"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
runtill \- start up a till or stock control terminal
.SH SYNOPSIS
.B runtill
.RI [ options ]
.SH DESCRIPTION
This manual page documents briefly the
.B runtill
command.
.PP
.\" TeX users may be more comfortable with the \fB<whatever>\fP and
.\" \fI<whatever>\fP escape sequences to invode bold face and italics, 
.\" respectively.
\fBruntill\fP is a program that enables an instance of the quicktill
system to be started, loading its configuration from a URL.
.SH OPTIONS
These programs follow the usual GNU command line syntax, with long
options starting with two dashes (\-\-).
A summary of options is included below.
For a complete description, see the Info files.
.TP
.B \-h, \-\-help
Show summary of options.
.TP
.B \-\-version
Show version of program.
.TP
.B \-u, \-\-config\-url=CONFIGURL
Provide the URL of the till configuration file; overrides the default
configured in /etc/quicktill/configurl
.TP
.B \-c, \-\-config\-number=CONFIGNUM
Indicate which configuration to use from the global configuration file.
The default is 0.
.TP
.B \-d, \-\-database=DATABASE
Override the database connection indicated in the configuration file.
Will usually have to be escaped, because the connection string is of
the form "dbname=foo host=bar"
.TP
.B \-l, \-\-logfile=LOGFILE
Specify a log filename.
.TP
.B \-\-debug
Include debug output in the logfile.
.SH AUTHOR
quicktill was written by <steve@greenend.org.uk>.
