#!/bin/bash

runtill testmenu file:testmenu.py \
	--commit-exit-code=10 \
	--quit-exit-code=20

if [ "$?" == "10" ]; then
  echo "Installing new menu file..."
  cp testmenu.py live/livemenu.py
  echo "Done."
else
  echo "NOT installing new menu file."
fi

